# Travis CI

sudo: required
dist: xenial
language: generic
python:
  - "2.7"
services:
  - docker
  
script:
  - cd ../../
  - git clone https://github.com/TechEmpower/FrameworkBenchmarks
  - cp -rf sumeetchhetri/ffead-cpp/docker/techempower-config/* FrameworkBenchmarks/frameworks/C++/ffead-cpp
  - cp -f sumeetchhetri/ffead-cpp/web/t1/include/*.h FrameworkBenchmarks/frameworks/C++/ffead-cpp/t1/include/
  - cp -f sumeetchhetri/ffead-cpp/web/t1/src/*.cpp FrameworkBenchmarks/frameworks/C++/ffead-cpp/t1/src/
  - cp -f sumeetchhetri/ffead-cpp/web/t2/include/*.h FrameworkBenchmarks/frameworks/C++/ffead-cpp/t2/include/
  - cp -f sumeetchhetri/ffead-cpp/web/t2/src/*.cpp FrameworkBenchmarks/frameworks/C++/ffead-cpp/t2/src/
  - cp -f sumeetchhetri/ffead-cpp/web/t3/include/*.h FrameworkBenchmarks/frameworks/C++/ffead-cpp/t3/include/
  - cp -f sumeetchhetri/ffead-cpp/web/t3/src/*.cpp FrameworkBenchmarks/frameworks/C++/ffead-cpp/t3/src/
  - cp -f sumeetchhetri/ffead-cpp/web/t4/include/*.h FrameworkBenchmarks/frameworks/C++/ffead-cpp/t4/include/
  - cp -f sumeetchhetri/ffead-cpp/web/t4/src/*.cpp FrameworkBenchmarks/frameworks/C++/ffead-cpp/t4/src/
  - cd FrameworkBenchmarks && ./tfb --mode verify --test-dir C++/ffead-cpp
  