[package]
name = "thruster-ffead-cpp"
version = "0.2.0"
authors = ["Sumeet Chhetri <sumeet.chhetri@gmail.com>"]
edition = "2021"

[dependencies]
hyper = "0.14.15"
futures = "0.1"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.71"
smallvec = "1.7.0"
thruster = "1.1.10"
thruster-proc = "1.1.10"
libc = "0.2.108"
bytes = "1.1.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
