[package]
name = "thruster-ffead-cpp"
version = "0.2.0"
authors = ["Sumeet Chhetri <sumeet.chhetri@gmail.com>"]
edition = "2021"

[dependencies]
hyper = "0.14.20"
futures = "0.3.21"
serde = "1.0.142"
serde_derive = "1.0.142"
serde_json = "1.0.83"
smallvec = "1.9.0"
thruster = "1.2.4"
thruster-proc = "1.2.4"
libc = "0.2.127"
bytes = "1.2.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
