name: Build docker image for TE (test)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image with wrk tests for ffead-cpp
      run: |
        cd docker/test
        chmod +x *.sh && ./build_test.sh
