name: Verify for TE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    steps:
    - uses: actions/checkout@v2
    - name: Verify tfb
      run: |
        cp -f docker/DockerFile-tfb-test FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp.dockerfile
        cp -rf docker/techempower-config/* FrameworkBenchmarks/frameworks/C++/ffead-cpp/
        cp -f docker/techempower-config/benchmark_config.json FrameworkBenchmarks/frameworks/C++/ffead-cpp/benchmark_config.json
        cd FrameworkBenchmarks
        ./tfb --mode verify --test-dir C++/ffead-cpp
