name: Benchmark docker image for TE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[docker_bench]')"
    steps:
    - uses: actions/checkout@v2
    - name: Build and benchmark the ffead-cpp-6.0 base docker image
      run: |
        git clone https://github.com/TechEmpower/FrameworkBenchmarks
        cd docker/techempower-config/
        cp -rf benchmark_config.json postgresql base/*.dockerfile lang/*.dockerfile scripts/*.sh *.sh *.dockerfile ../../FrameworkBenchmarks/frameworks/C++/ffead-cpp/
        cd ../../FrameworkBenchmarks
        ./tfb --mode benchmark --test just drogon ffead-cpp-v-picov ffead-cpp-postgresql-raw-profiled ffead-cpp-postgresql-raw-async-profiled ffead-cpp-postgresql-raw-async-pool-profiled
        cd results/20* && cat results.json