name: Compare benchmark ffead-cpp versions 5.2 and 5.3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[docker_compare]')"
    steps:
    - uses: actions/checkout@v2
    - name: Compare benchmark ffead-cpp versions 5.2 and 5.3
      run: |
        git clone https://github.com/TechEmpower/FrameworkBenchmarks
        cp -rf docker/techempower-config/* FrameworkBenchmarks/frameworks/C++/ffead-cpp/
        cp docker/benchmark_compare.json FrameworkBenchmarks/frameworks/C++/ffead-cpp/benchmark_config.json
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-v-picov.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-v-picov52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-v-picov52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-v-picov.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-v-picov53.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw53.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-profiled52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-profiled52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-profiled53.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-clibpqb-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-clibpqb-profiled52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-clibpqb-profiled52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-clibpqb-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-clibpqb-profiled53.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async53.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-profiled52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-profiled52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-profiled53.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-clibpqb-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-clibpqb-profiled52.dockerfile
        sed -i 's|:5.3|:5.2|g' FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-clibpqb-profiled52.dockerfile
        cp FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-clibpqb-profiled.dockerfile FrameworkBenchmarks/frameworks/C++/ffead-cpp/ffead-cpp-postgresql-raw-async-clibpqb-profiled53.dockerfile
        cd FrameworkBenchmarks
        ./tfb --mode benchmark --test-dir C++/ffead-cpp
        cd results/20* && cat results.json