name: Nodejs + ffead-cpp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    steps:
    - uses: actions/checkout@v4
    - name: Build ffead-cpp with nodejs backend
      run: |
        cd lang-server-backends/javascript/nodejs
        docker build -f ffead-cpp-nodejs-http.dockerfile .
        