name: Scons build

on:
  push:
    branches: [ master ]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    steps:
    - uses: actions/checkout@v4
    - name: Build ffead-cpp with scons
      run: |
        cd docker/os-based
        docker build -f DockerFile-Ubuntu-x64-ffead-cpp-scons .
