name: Windows Mingw-w64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows-mingw:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    strategy:
      matrix:
        os: [windows-2019]
        vs: [2019]
    steps:
    - uses: actions/checkout@v4
    - name: Set ENV
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        echo "::add-path::C:\msys64\mingw64\bin"
        echo "::add-path::C:\msys64\usr\bin"
    - name: Update msys package db
      run: |
        pacman -Syu --noconfirm
#    - name: Update base packages
#      run: |
#        pacman -Su --noconfirm
    - name: Install packages
      run: |    
        pacman -S --noconfirm make
        pacman -S --noconfirm procps
        pacman -S --noconfirm git
        pacman -S --noconfirm wget
        pacman -S --noconfirm curl
        pacman -S --noconfirm gdb
        pacman -S --noconfirm mingw-w64-x86_64-oniguruma
        pacman -S --noconfirm mingw-w64-x86_64-gcc
        pacman -S --noconfirm mingw-w64-x86_64-make
        pacman -S --noconfirm mingw-w64-x86_64-curl
        pacman -S --noconfirm mingw-w64-x86_64-openssl
        pacman -S --noconfirm mingw-w64-x86_64-zlib
        pacman -S --noconfirm mingw-w64-x86_64-jsoncpp
        pacman -S --noconfirm mingw-w64-x86_64-crt
        pacman -S --noconfirm mingw-w64-x86_64-headers
        pacman -S --noconfirm mingw-w64-x86_64-readline
        pacman -S --noconfirm mingw-w64-x86_64-cmake
        pacman -S --noconfirm mingw-w64-x86_64-dlfcn
        pacman -S --noconfirm mingw-w64-x86_64-unixodbc
        pacman -S --noconfirm mingw-w64-x86_64-extra-cmake-modules
        pacman -S --noconfirm mingw64/mingw-w64-x86_64-cyrus-sasl
        pacman -S --noconfirm mingw-w64-x86_64-postgresql
        pacman -S --noconfirm mingw-w64-x86_64-ninja
        pacman -S --noconfirm mingw-w64-x86_64-hiredis
        pacman -S --noconfirm diffutils
        pacman -S --noconfirm unzip
        pacman -S --noconfirm dos2unix
        echo 'Installed all dependencies'
    - name: Install dependencies and ffead-cpp
      run: |
        bash --login -c "export PATH=/mingw64/bin:/usr/bin:$PATH && cd /tmp && wget https://raw.githubusercontent.com/sumeetchhetri/ffead-cpp/master/docker/install_mingw.sh && dos2unix install_mingw.sh && chmod +x install_mingw.sh && ./install_mingw.sh"
        #set ErrorLevel=%ErrorLevel%
        #IF ($ErrorLevel -ne 0) { exit 1 }
        #exit 0
